#!/bin/bash
finish() {
    user_id=$(stat -c '%u:%g' /data)
    chown -R ${user_id} /data
}
trap finish EXIT

set -e
git submodule update --init
mkdir BUILD || :
cd BUILD
cmake .. -DCMAKE_BUILD_TYPE=coverage
make all
../scripts/coverage
