#!/bin/bash
finish() {
    ./scripts/ci/fixup-docker-owner
}
trap finish EXIT

set -e
git submodule update --init
mkdir BUILD || :
cd BUILD
cmake .. -DCMAKE_BUILD_TYPE=coverage
make all
../scripts/coverage
