#!/bin/bash
set -e
./docker/build-all
git submodule update --init
[ -d _build/gcov-coverage ] || mkdir -p _build/gcov-coverage
[ -d _build/.ccache ] || mkdir -p _build/.ccache
DOCKER_NONINTERACTIVE=1 ./docker/s80x86-build -e -c 'cd _build/gcov-coverage; \
        cmake ../.. -DCMAKE_BUILD_TYPE=Coverage; \
        make; \
        ctest; \
        ../../scripts/gcovr --delete --output=coverage.xml --gcov-exclude=".*googletest.*" --gcov-exclude="tests.*" --root=../.. --xml-pretty --exclude-unreachable-branches .; \
        ../../scripts/verilator-cobertura --output=coverage-rtl-unittest.xml --source-root=../.. ./tests/rtl/coverage/rtl-unittest.dat; \
        rm ../../*.gcov'
