#!/bin/bash
set -e
./docker/build-all
git submodule update --init
mkdir BUILD || :
./docker/s80x86-build -e -c 'cd BUILD; \
        cmake .. -DCMAKE_BUILD_TYPE=coverage; \
        make -j8; \
        mkdir test_results; \
        ./tests/unittest --gtest_output=xml:test_results/simulation.xml; \
        ./tests/rtl/rtl-unittest --gtest_output=xml:test_results/rtl.xml; \
        rm -rf Testing; \
        ctest -T Test'
