#!/bin/bash
set -e
./docker/build-all
git submodule update --init
[ -d BUILD-unittest ] || mkdir BUILD-unittest
DOCKER_NONINTERACTIVE=1 ./docker/s80x86-build -e -c 'cd BUILD-unittest; \
        cmake .. -DCMAKE_BUILD_TYPE=coverage; \
        make -j8; \
        [ -d test_results ] || mkdir test_results; \
        ./tests/unittest --gtest_output=xml:test_results/simulation.xml; \
        ./tests/rtl/rtl-unittest --gtest_output=xml:test_results/rtl.xml; \
        rm -rf Testing; \
        ctest -T Test'
