#!/bin/bash
set -e
tar --exclude=.git* --exclude=.exrc --exclude=.ycm_extra_conf.py --exclude=_build --exclude=*.tar.xz --transform="s|^80x86|80x86-$(date +%Y%m%d)|g" -C .. 80x86 -cJf ../80x86-$(date +%Y%m%d).tar.xz
mv ../80x86-$(date +%Y%m%d).tar.xz .
