#!/bin/bash

# Copyright Jamie Iles, 2017
#
# This file is part of s80x86.
#
# s80x86 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# s80x86 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with s80x86.  If not, see <http://www.gnu.org/licenses/>.

set -e
tar --exclude=scripts/archive \
    --exclude=scripts/run-dev-unittest \
    --exclude=.git* \
    --exclude=.exrc \
    --exclude=.ycm_extra_conf.py \
    --exclude=_build \
    --exclude=*.tar.xz \
    --exclude=*.pyc \
    --exclude=*.pyo \
    --exclude=__pycache__ \
    --exclude=.*.swp \
    --exclude=.*.swo \
    --transform="s|^80x86|80x86-$(date +%Y%m%d)|g" -C .. 80x86 -cJf ../80x86-$(date +%Y%m%d).tar.xz
mv ../80x86-$(date +%Y%m%d).tar.xz .
