#!/bin/bash

# Copyright Jamie Iles, 2017
#
# This file is part of s80x86.
#
# s80x86 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# s80x86 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with s80x86.  If not, see <http://www.gnu.org/licenses/>.

set -e
./docker/build-all
[ -d .git ] && git submodule update --init
[ -d _build/.ccache ] || mkdir -p _build/.ccache
[ -d _build/build ] || mkdir -p _build/build
DOCKER_NONINTERACTIVE=1 ./docker/s80x86-build -e -c 'cd _build/build; \
        cmake -GNinja ../.. ; \
        ninja all; \
        ctest -LE JTAG --output-on-failure;'
