#!/bin/bash

# Run from inside the CMake build directory after configuring with
# -DCMAKE_BUILD_TYPE=COVERAGE
set -e
lcov --directory ./sim/CMakeFiles/8086sim.dir/ --directory ./tests/CMakeFiles/unittest.dir/ --zerocounters -q
ctest
lcov --directory ./sim/CMakeFiles/8086sim.dir/ --directory ./tests/CMakeFiles/unittest.dir/ -c -o 8086sim.info -q --rc lcov_excl_line=__builtin_unreachable
# Remove system headers etc.
lcov --remove 8086sim.info "/usr*" -o 8086sim.info -q
lcov --remove 8086sim.info "4.*" -o 8086sim.info -q
lcov --remove 8086sim.info "googletest/*" -o 8086sim.info -q
rm -rf test_coverage
genhtml -o test_coverage 8086sim.info
