#!/usr/bin/env python
import sys

with open(sys.argv[1]) as font:
    font_data = font.read()

with open(sys.argv[2], 'w') as outfile:
    for c in font_data:
        for i in range(7,-1,-1):
            outfile.write('1\n' if (ord(c) & (1 << i)) else '0\n')
